name: "🔖 Bookmarks from Dev.to and daily.dev"

on:
  workflow_dispatch:
  schedule:
    - cron: '1 */24 * * *' # Runs every 5 minutes

jobs:
  update_reading_list:
    name: "Update reading list"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "Run a one-line script"
        run: echo Hello, world!
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
        with:
            node-version: 16
      - run: npm ci
      - run: npm start
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEV_EMAIL: ${{ secrets.DEV_EMAIL }}
          DEV_PASSWORD: ${{ secrets.DEV_PASSWORD }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          DAILYDEV_BOOKMARK_RSS_URL: ${{ secrets.DAILYDEV_BOOKMARK_RSS_URL }}
