name: "🔖 Reading list Dev.to"

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  update_reading_list:
    name: "Update reading list"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "Run a one-line script"
        run: echo Hello, world!
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
        with:
            node-version: 16
      # - name: Create .env file
      #   uses: SpicyPizza/create-envfile@v1
      #   with:
      #     envkey_DEV_EMAIL: ${{ secrets.DEV_EMAIL }}
      #     envkey_DEV_PASSWORD: ${{ secrets.DEV_PASSWORD }}

      - run: npm ci
      - run: npm start
        
#       - name: Run a main script
#         run: 'lib/index.js'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEV_EMAIL: ${{ secrets.DEV_EMAIL }}
          DEV_PASSWORD: ${{ secrets.DEV_PASSWORD }}
